title:              Yuri Notes
email:              qiuyu1819@gmail.com
description:        A place where I document thoughts
author:             Yuri Qiu
baseurl:            "/"
url:                "https://yuriqiu.github.io"

# Social Profiles 
github_username: YuriQiu 

# Build settings
markdown:           kramdown
paginate:           20
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
