title:              Yuri's Notebook
email:              qiuyu1819@gmail.com
description:        A place that records my thoughts
author:             Start Bootstrap
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://yuriqiu.github.io"

# Social Profiles 
github_username: Yuri Qiu 

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
